export const localization = {
  en: {
    dir: 'ltr',
    brand: 'Knowledge Garden',
    classroomTitle: 'The Garden Base',
    tagline: 'Cultivate Your Skills',
    subtitle: 'Grow from a seedling to a tech giant in our futuristic digital ecosystem.',
    plant_seed: 'Plant Your First Seed',
    explore: 'Explore Gardens',
    available_gardens: 'Available Gardens',
    features: 'Features',
    no_gardens_available: 'No gardens available at the moment.',
    no_garden_seeds: 'No seeds available in this garden yet.',
    choose_spec: 'Choose your specialisation and start cultivating expertise.',
    total_earnings: 'Total Harvest Earnings',
    active_seekers: 'Active Seekers',
    growth_rate: 'Growth Rate',
    brand_subtitle: 'The Neural E-Learning Ecosystem',
    new_era: 'THE NEXT AGE OF SOFTWARE EDUCATION',
    hero_title_prefix: 'Root Your Expertise in the',
    hero_title_highlight: 'Knowledge Garden',
    hero_title_suffix: '',
    realtime_status: 'REALTIME CORES OPERATING',
    plant_skill: 'Plant Seed',
    open_garden: 'Open Garden',
    my_gardens: 'My Gardens',
    secure_inbox: 'Mock Secure Inbox',
    view_profile: 'View Profile',
    membership_paid: 'PAID',
    membership_free: 'FREE',
    currency_egp: 'EGP',
    currency_try: 'TRY',
    admin_title: 'Admin Panel',
    system_controller: 'System Controller',
    security_logs: 'Security Logs',
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    courses: 'Gardens',
    users: 'Seekers',
    settings: 'Settings',
    view_all: 'View All',
    launch_course: 'Launch New Garden',
    last_seen: 'Last Seen',
    ip_address: 'IP Address',
    device: 'Device',
    location: 'Location',
    search_placeholder: 'Search by name or email...',
    new_registrations: 'New Registrations',
    avg_growth_rate: 'Avg Growth Rate',
    security_alerts: 'Security Alerts',
    chat_instructor: 'Chat with Instructor',
    chat_placeholder: 'Type your message to the instructor...',
    chat_send: 'Send Message',
    chat_transmitting: 'Transmitting...',
    forgot_password: 'Forgot Password?',
    forgot_password_title: 'Reset Security Credentials',
    forgot_password_subtitle: 'Enter your email to receive a synchronization reset key.',
    send_reset_btn: 'Send Reset Key',
    reset_success_msg: 'Reset key dispatched! Check your secure inbox.',
    storage_used: 'Storage Used',
    login_title: 'Log In',
    logout_session: 'Logout Session',
    email_placeholder: 'gardener@knowledge.io',
    password_placeholder: '••••••••',
    phone_placeholder: '+20123456789 or +905...',
    sync_key_placeholder: '6-digit sync key',
    login_subtitle: 'Continue your journey into the Knowledge Garden.',
    email_address: 'Email Address',
    phone_wallet_num: 'Phone / Wallet Number',
    register_subtitle: 'Gain a verified secure student seed account.',
    email_or_phone: 'Email or Phone',
    password: 'Password',
    already_have_account: 'Already have an account? Log In',
    quick_demo_login: 'Quick Sandbox Auto-Login',
    new_to_garden: 'New to the Garden?',
    create_account: 'Create Garden Account',
    verify_title: 'Verify Your Identity',
    verify_subtitle: 'A secure seed has been sent to your email/phone. Please enter the 6-digit synchronization code below.',
    verify_btn: 'Verify Growth',
    resend_timer: 'Resend available in',
    resend_btn: 'Resend Code',
    classroom_seeds: 'Garden Seeds',
    classroom_rooted: 'Rooted',
    classroom_path: 'Classroom Path',
    progress_tracking: 'Track your learning journey',
    of: 'of',
    total: 'Total',
    remaining: 'Remaining',
    ask_question: 'Ask a Question',
    question_placeholder: 'What is on your mind, gardener? Dig deep...',
    post_btn: 'Post Query',
    watermark_text: 'Student Data Secured',
    country_switch: 'Country',
    egypt: 'Egypt (EGP)',
    turkey: 'Turkey (TRY)',
    payment_method: 'Payment Method',
    mobile_wallet: 'Mobile Wallet (Vodafone Cash)',
    instapay: 'InstaPay Transfer',
    credit_card: 'Credit / Debit Card',
    papara: 'Papara Wallet',
    checkout_title: 'Checkout Sandbox',
    checkout_btn: 'Initiate Secure Growth',
    price_label: 'Price',
    secure_badge: 'SECURE ACCESS',
    need_help: 'Need help? Contact support',
    notebook_title: 'Digital Notebook',
    add_note_btn: 'Save Note',
    note_placeholder: 'Write a timestamped note, question, or reference here...',
    capture_time: 'Capture timestamp',
    no_notes: 'Your notebook is empty. Select a timestamp to plant a smart thought!',
    user_page_title: 'Student Profile Portal',
    user_page_badge: 'VERIFIED CULTIVATOR',
    enrolled_gardens: 'Enrolled Gardens',
    completed_seeds: 'Completed Seeds',
    account_id: 'Account ID',
    security_level: 'Security Clearance',
    membership_tier: 'Membership Grade',
    registered_phone: 'Linked Mobile',
    joined_on: 'Enrolled On',
    back_to_classroom: 'Back to Classroom',
    back_to_landing: 'Back to Gardens',
    rights_reserved: 'All rights reserved.',
    my_gardens_desc: 'Your enrolled gardens - continue learning',
    enrolled_badge: 'Enrolled',
    pending_approval: 'Pending Approval',
    previous_seed: 'Previous Seed',
    next_seed: 'Next Seed',
    no_queries_yet: 'No questions for this seed yet. Be the first to start the root thread!',
    search_notes: 'Search your notes...',
    download_notes: 'Download notes',
    play_from_here: 'Play from here',
    delete_message: 'Delete Message',
    delete_confirm: 'Permanently delete this message?',
    seed_not_completed: 'Seed not completed yet',
    complete_seed_first: 'You must complete the seed first before accessing the quiz.',
    no_quiz_questions: 'No quiz questions for this seed',
    quiz_review: 'Quiz Review',
    knowledge_check: 'KNOWLEDGE CHECK',
    question_of: 'Question {current} of {total}',
    confirm_answer: 'CONFIRM ANSWER',
    checking_answer: 'Authorizing knowledge seed check...',
    incorrect_review: 'Incorrect answer. Please review the seed details and try again!',
    try_again_btn: 'TRY AGAIN',
    correct_excellent: 'Excellent! Perfect answer verified successfully!',
    next_question: 'NEXT QUESTION',
    complete: 'COMPLETE',
    previous_answer_incorrect: 'Previous answer was incorrect. Try again!',
    retry_btn: 'RETRY',
    correct_answer: 'Correct answer!',
    incorrect_try_again: 'Incorrect. Try again!',
    previous: 'Previous',
    next: 'Next',
    stream_error: 'Video playback error. Please try again.',
    stream_auth_failed: 'Failed to authenticate stream.',
    please_complete_checkout: 'Please complete the secure gateway checkout or re-login to renew stream license tokens.',
    checkout_success_title: 'Cultivation Authorized!',
    checkout_transaction_msg: 'Transaction {id} verified on server.',
    checkout_redirecting: 'Syncing growth context, please wait...',
    scan_or_copy: 'Scan or Copy to Pay',
    send_exact_amount: 'Please send exactly {amount} {currency} to unlock your digital garden.',
    upload_screenshot: 'Upload Payment Screenshot',
    confirm_phone_label: 'Confirm your Phone / IPA used for transfer',
    mobile_wallet_number: 'Mobile Wallet Number',
    papara_account: 'Papara Wallet Account',
    secure_card_input: 'Secure Card Input',
    card_number: 'Card Number',
    card_expiry: 'MM/YY',
    card_cvv: 'CVV',
    verifying_payment: 'Verifying Neural Pipeline...',
    payment_required_alert: 'Please fill in all required fields',
    drag_drop_browse: 'Drag & drop or browse your confirmation screenshot',
    screenshot_attached: 'Screenshot Attached - Click to Replace',
    encryption_notice: 'This conversation is end-to-end encrypted via Knowledge Garden protocols.',
    refresh_analytics: 'Refresh Analytics',
    close_panel: 'Close',
    tab_cms: 'Knowledge Base (CMS)',
    tab_queries: 'Pending Queries',
    tab_users: 'Student Accounts',
    tab_payments: 'Payments',
    tab_audit_logs: 'Audit Logs',
    tab_quiz_management: 'Quiz Management',
    tab_quiz_degrees: 'Quiz Degrees',
    quiz_degrees_title: 'All Users Quiz Degrees',
    quiz_degrees_desc: 'Review quiz performance scores for all students',
    no_quiz_data: 'No quiz data available yet.',
    loading: 'Loading...',
    name_col: 'Name',
    questions_col: 'Questions',
    correct_col: 'Correct',
    wrong_col: 'Wrong',
    score_col: 'Score',
    stat_student_answers: 'Student Answer Statistics',
    stat_answers_submitted: 'Answers Submitted',
    create_garden: 'Create Garden',
    embed_seed: 'Embed Knowledge Seed',
    no_seeds_yet: 'No seeds linked to this garden yet.',
    harvest_egypt: 'Harvest Egypt',
    harvest_turkey: 'Harvest Turkey',
    seekers_registered: 'Seekers Registered',
    active_now: 'Active Now',
    garden_cms_manager: 'Garden Cultivator Manager',
    cms_subtitle: 'Nourish lessons and digital gardens in the system ecosystem',
    type_answer_here: 'Type answer here...',
    no_student_queries: 'No student queries pending response! Garden is clear.',
    weekly_analytics: 'Weekly Seed Harvest Analytics (recharts)',
    edit: 'Edit',
    del: 'Del',
    quiz_short: 'Quiz',
    hide_seeds: 'Hide Seeds',
    view_seeds: 'View Seeds',
    linked_seeds: 'Linked Seeds',
    toggle_access: 'Toggle Access',
    reply: 'Reply',
    search_mail: 'Search secure letters...',
    select_mail: 'SELECT A SECURE TELEMETRY MAIL',
    status_online: 'ONLINE & VERIFIED',
    status_fallback: 'FALLBACK SANDBOX ONLY',
    verification_secure_key: 'VERIFICATION SECURE KEY',
    cryptographic_seal: 'KNOWLEDGE ECOSYSTEM CRYPTOGRAPHIC SEAL ACTIVE',
    my_gardens_desc_continue: 'Your enrolled gardens - continue learning',
    student_growth_metrics: 'Student Growth Metrics',
    seeds_bloomed: 'Seeds Bloomed',
    currently_studying: 'CURRENTLY STUDYING',
    completed: 'Completed',
    total_seeds: 'total seeds',
    no_matching_seeds: 'No matching seeds',
    adjust_filters: 'Try adjusting your sorting or filter choices',
    sort_by: 'Sort By:',
    default_order: 'Default Syllabus Order',
    difficulty_low_high: 'Difficulty: Low to High',
    difficulty_high_low: 'Difficulty: High to Low',
    duration_short_long: 'Duration: Short to Long',
    duration_long_short: 'Duration: Long to Short',
    skill_tag_count: 'Skill Tag Count: High to Low',
    skill_tag: 'Skill Tag',
    duration: 'Duration',
    difficulty: 'Difficulty',
    refine_reorder: 'Refine & Reorder',
    reset: 'Reset',
    select_difficulty: 'Select Difficulty Level:',
    select_duration: 'Select Class Duration:',
    select_skill_tag: 'Select Target Skill Tag:',
    previous_classroom: 'Classroom Path:',
    garden_questions_manager: 'Garden Questions Manager (CMS FAQ)',
    seekers_registry: 'Seekers Registry (User State)',
    email_col: 'Email',
    phone_col: 'Phone',
    paid_gardens_col: 'Paid Gardens',
    verification_col: 'Verification',
    session_key_col: 'JWT Session Key',
    actions_col: 'Actions',
    session_closed: 'CLOSED',
    verified: 'Verified',
    pending_verification: 'Pending Verification',
    gardens_count_suffix: 'GARDEN(S)',
    none: 'NONE',
    smtp_diagnostics: 'NodeMailer OTP System Diagnostics',
    smtp_status: 'Verifying live SMTP carrier pipeline and credential status',
    smtp_indicator: 'SMTP Active Status Indicator:',
    credentials_registry: 'Active Credentials Registry',
    smtp_host: 'SMTP Host:',
    smtp_port: 'SMTP Port:',
    smtp_user: 'SMTP User:',
    smtp_from: 'Dispatcher From:',
    credential_state: 'Credential State:',
    smtp_test: 'SMTP Live Test Pipeline',
    smtp_test_desc: 'Dispatches an instantaneous high-security test email to double-check delivery logs.',
    email_placeholder_smtp: 'recipient@example.com',
    sending: 'Sending...',
    send_test: 'Send Test Email',
    quiz_management_title: 'Quiz Management',
    quiz_management_desc: 'Create, edit, and monitor knowledge check questions',
    refresh_quiz_data: 'Refresh Quiz Data',
    system_audit_logs: 'System Audit Logs',
    audit_log_subtitle: 'Immutable record of all administrative actions',
    search_logs: 'Search logs...',
    no_matching_logs: 'No matching log entries found.',
    no_logs: 'No audit logs have been recorded yet.',
    no_transactions: 'No transaction records found in the ledger.',
    pending_status: 'PENDING',
    approve_btn: 'Approve',
    reject_btn: 'Reject',
    export_csv: 'Export CSV',
    txn_id_col: 'TXN ID',
    seeker_email_col: 'Seeker Email',
    garden_id_col: 'Garden ID',
    amount_col: 'Amount',
    gateway_col: 'Gateway',
    proof_col: 'Proof',
    status_col: 'Status',
    timestamp_col: 'Timestamp',
    transaction_history: 'Transaction History',
    audit_log_desc: 'Audit log of all student financial records',
    smtp_missing_creds: 'Missing credentials in Secrets Panel. Registration and Reports OTP codes will only print dynamically via local sandbox console & simulated mail tray helper.',
    smtp_dispatch_success: 'Dispatch Success!',
    message_id: 'Message ID:',
    smtp_delivery_refused: 'Delivery Refused:',
    smtp_pass_loaded: 'SMTP_PASS Loaded (AES-256 Secured)',
    not_configured: 'Not configured',
    garden: 'Garden',
    seed: 'Seed',
    confirm_delete: 'Are you absolutely sure you want to delete this entity?',
    answer_post_timeout: 'Answer post timed out.',
    approval_failed: 'Approval failed',
    approval_request_failed: 'Approval request failed',
    rejection_failed: 'Rejection failed',
    rejection_request_failed: 'Rejection request failed',
    deletion_error: 'Deletion Error',
    cms_update_error: 'CMS Update Error',
    bulk_limit_reached: 'High-Speed Fiber CDN Limit reached: Only the first 50 entries will be queued for this session.',
    populate_lectures: 'Please populate the lectures grid first using either Quick Generator or Paste Form.',
    select_target_garden: 'Please select a valid target course garden.',
    bulk_insert_failed: 'Bulk insertion failed at server level.',
    network_upload_error: 'Network upload anomaly detected: ',
    gardens: 'Gardens',
    all_gardens: 'All Gardens',
    back_to_home: 'Back to Home',
    browse_gardens: 'Browse All Gardens',
    discover_courses: 'Discover all available courses and start learning',
    full_name: 'Full Name',
    full_name_placeholder: 'e.g. John Doe',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    difficult: 'Advanced',
    short_duration: 'Short (< 15m)',
    medium_duration: 'Medium (15-30m)',
    long_duration: 'Long (30m+)',
    payment_verified_pending: 'Your payment is currently being verified. Please wait for admin approval.',
    payment_approved: 'Payment Approved!',
    payment_rejected: 'Payment Rejected',
    access_activated: 'Your full garden access has been activated.',
    check_inbox_details: 'Please check your inbox for details.',
    skills_acquired: 'Curriculum Skills & Distributed System Management',
    ai_advice: 'We recommend continuous learning to ensure professional growth.',
    otp_dispatched: 'Security verification OTP dispatched to your secure inbox!',
    otp_verified: 'OTP successfully verified! Your Growth Report has been issued.',
    report_instruction: 'Nurture all seeds in this Garden to 100% to generate your high-security Growth Report & Certificate.',
    garden_complete: 'Congratulations! Garden 100% Cultivate-Bloomed!',
    request_report: 'Request Growth Report & Certificate',
    report_otp_label: 'Report Verification Key (OTP)',
    verify_certificate: 'Verify & Unlock Certificate',
    otp_instruction: 'Open upper [Mock Inbox] envelope client to extract your security PIN.',
    certificate_issued: 'Official Certificate Issued!',
    view_report: 'View Growth Report & Certificate',
  },
  ar: {
    dir: 'rtl',
    brand: 'حديقة المعرفة',
    classroomTitle: 'قاعدة الحديقة',
    tagline: 'حديقة المعرفة ',
    subtitle: 'نمِ مهاراتك في نظام بيئي رقمي متطور. حدائقنا توفر البيئة المثالية لتنمو من بذرة إلى عملاق تقني.',
    plant_seed: 'ازرع بذرتك الأولى',
    explore: 'استكشف الحدائق',
    available_gardens: 'الحدائق المتاحة',
    features: 'الميزات',
    no_gardens_available: 'لا توجد حدائق متاحة حالياً.',
    no_garden_seeds: 'لا توجد بذور متاحة في هذه الحديقة بعد.',
    choose_spec: 'اختر تخصصك وابدأ في زراعة وتنمية خبراتك.',
    total_earnings: 'إجمالي أرباح الحصاد',
    active_seekers: 'الباحثون النشطون',
    growth_rate: 'معدل النمو',
    brand_subtitle: 'حديقة المعرفة العصبية',
    new_era: 'العصر الجديد للدراسة',
    hero_title_prefix: 'اكتشف قوة',
    hero_title_highlight: 'حديقة المعرفة',
    hero_title_suffix: '',
    realtime_status: 'أنظمة النواة تعمل بالوقت الفعلي',
    plant_skill: 'ازرع مهارة',
    open_garden: 'افتح الحديقة',
    my_gardens: 'حدائقي',
    secure_inbox: 'صندوق الوارد الآمن',
    view_profile: 'عرض الملف الشخصي',
    membership_paid: 'تنشيط',
    membership_free: 'محدود',
    currency_egp: 'ج.م',
    currency_try: 'ليرة',
    admin_title: 'لوحة التحكم',
    system_controller: 'مراقب النظام',
    security_logs: 'سجلات الأمان',
    dashboard: 'لوحة القيادة',
    analytics: 'التحليلات',
    courses: 'الحدائق المعرفية',
    users: 'الباحثون',
    settings: 'الإعدادات',
    view_all: 'عرض الكل',
    launch_course: 'إطلاق حديقة جديدة',
    last_seen: 'آخر ظهور',
    ip_address: 'عنوان IP',
    device: 'الجهاز',
    location: 'الموقع',
    search_placeholder: 'ابحث بالاسم أو البريد...',
    new_registrations: 'التسجيلات الجديدة',
    avg_growth_rate: 'متوسط معدل النمو',
    security_alerts: 'التنبيهات الأمنية',
    chat_instructor: 'التحدث مع المحاضر',
    chat_placeholder: 'اكتب رسالتك للمحاضر هنا...',
    chat_send: 'إرسال الرسالة',
    chat_transmitting: 'جاري الإرسال...',
    forgot_password: 'هل نسيت كلمة المرور؟',
    forgot_password_title: 'إعادة تعيين أمان الحساب',
    forgot_password_subtitle: 'أدخل بريدك الإلكتروني لاستلام مفتاح إعادة المزامنة.',
    send_reset_btn: 'إرسال مفتاح الإعادة',
    reset_success_msg: 'تم إرسال مفتاح الإعادة! تفقد صندوق الوارد الآمن.',
    storage_used: 'المساحة المستخدمة',
    login_title: 'تسجيل الدخول',
    logout_session: 'تسجيل الخروج',
    email_placeholder: 'gardener@knowledge.io',
    password_placeholder: '••••••••',
    phone_placeholder: '+20123456789 أو +905...',
    sync_key_placeholder: 'مفتاح مزامنة مكون من 6 أرقام',
    login_subtitle: 'تابع رحلتك التعليمية داخل حديقة المعرفة.',
    email_address: 'البريد الإلكتروني',
    phone_wallet_num: 'الهاتف / رقم المحفظة',
    register_subtitle: 'احصل على حساب طالب آمن وموثق لزراعة البذور.',
    email_or_phone: 'البريد الإلكتروني أو الهاتف',
    password: 'كلمة المرور',
    already_have_account: 'لديك حساب بالفعل؟ تسجيل الدخول',
    quick_demo_login: 'تسجيل دخول سريع لبيئة التجربة',
    new_to_garden: 'جديد في الحديقة؟',
    create_account: 'أنشئ حسابًا',
    verify_title: 'التحقق من الهوية',
    verify_subtitle: 'تم إرسال رمز أمان إلى هاتفك / بريدك. يرجى إدخال الرمز المكون من 6 أرقام لتنشيط الحساب.',
    verify_btn: 'تأكيد النمو',
    resend_timer: 'إعادة الإرسال متاح خلال',
    resend_btn: 'إعادة إرسال الرمز',
    classroom_seeds: 'بذور المعرفة',
    classroom_rooted: 'مترسخ',
    classroom_path: 'مسار الفصل',
    progress_tracking: 'تتبع رحلة التعلم الخاصة بك',
    of: 'من',
    total: 'الإجمالي',
    remaining: 'المتبقي',
    ask_question: 'طرح استفسار',
    question_placeholder: 'ما الذي يدور في ذهنك يا مزارع؟ احفر بعمق...',
    post_btn: 'نشر الاستفسار',
    watermark_text: 'تم تأمين بيانات الطالب',
    country_switch: 'الدولة',
    egypt: 'مصر (EGP)',
    turkey: 'تركيا (TRY)',
    payment_method: 'طريقة الدفع',
    mobile_wallet: 'محفظة الهاتف الذكي (فودافون كاش)',
    instapay: 'تحويل إنستاباي',
    credit_card: 'بطاقة ائتمان / ميزة',
    papara: 'محفظة Papara رقمية',
    checkout_title: 'بوابة الدفع التجريبية',
    checkout_btn: 'بدء الرعاية الآمنة',
    price_label: 'السعر',
    secure_badge: 'دخول آمن للمنصة',
    need_help: 'هل تحتاج إلى مساعدة؟ تواصل مع الدعم',
    notebook_title: 'المذكرة الرقمية',
    add_note_btn: 'حفظ الملاحظة',
    note_placeholder: 'اكتب ملاحظة مقرونة بطابع زمني هنا...',
    capture_time: 'التقاط طابع زمني',
    no_notes: 'مذكرتك فارغة. التقط طابعاً زمنياً واسرع في تدوين أفكارك الذكية!',
    user_page_title: 'بوابة الملف الشخصي للباحث',
    user_page_badge: 'مزارع معتمد وموثق',
    enrolled_gardens: 'الحدائق النشطة',
    completed_seeds: 'البذور النامية',
    account_id: 'معرف الحساب الرقمي',
    security_level: 'مستوى التخليص الأمني',
    membership_tier: 'رتبة الباحث',
    registered_phone: 'الهاتف الموثق',
    joined_on: 'تاريخ الانتساب',
    back_to_classroom: 'العودة لقاعة الدراسة',
    back_to_landing: 'العودة للأكاديمية وتصفح الحدائق',
    rights_reserved: 'جميع الحقوق محفوظة.',
    my_gardens_desc: 'حدائقك المشتركة - تابع تعلمك',
    enrolled_badge: 'مفعل',
    pending_approval: 'قيد المراجعة',
    previous_seed: 'البذرة السابقة',
    next_seed: 'البذرة التالية',
    no_queries_yet: 'لا توجد استفسارات لهذه البذرة بعد. كن الأول لمناقشتها!',
    search_notes: 'بحث في ملاحظاتك...',
    download_notes: 'تنزيل الملاحظات',
    play_from_here: 'تشغيل من هنا',
    delete_message: 'حذف الرسالة',
    delete_confirm: 'هل أنت متأكد من حذف هذه الرسالة نهائياً؟',
    seed_not_completed: 'البذرة لم تكتمل بعد',
    complete_seed_first: 'يجب إكمال مشاهدة البذرة أولاً قبل فتح الاختبار.',
    no_quiz_questions: 'لا توجد أسئلة اختبار لهذه البذرة',
    quiz_review: 'مراجعة الاختبار',
    knowledge_check: 'اختبار المعرفة التفاعلي',
    question_of: 'سؤال {current} من {total}',
    confirm_answer: 'تأكيد الإجابة',
    checking_answer: 'جاري التحقق من الإجابة...',
    incorrect_review: 'إجابة خاطئة. يرجى مراجعة البذرة والمحاولة مجدداً!',
    try_again_btn: 'إعادة المحاولة',
    correct_excellent: 'رائع! إجابة صحيحة ومطابقة للمعايير!',
    next_question: 'السؤال التالي',
    complete: 'إكمال',
    previous_answer_incorrect: 'كانت إجابتك السابقة خاطئة. حاول مرة أخرى!',
    retry_btn: 'إعادة المحاولة',
    correct_answer: 'إجابة صحيحة!',
    incorrect_try_again: 'إجابة خاطئة. حاول مرة أخرى!',
    previous: 'السابق',
    next: 'التالي',
    stream_error: 'حدث خطأ في تشغيل الفيديو. حاول مرة أخرى.',
    stream_auth_failed: 'فشل التحقق من البث.',
    please_complete_checkout: 'يرجى إكمال عملية الدفع أو إعادة تسجيل الدخول لتجديد تراخيص البث.',
    checkout_success_title: 'اكتملت الرعاية بنجاح!',
    checkout_transaction_msg: 'تم التحقق من المعاملة {id} على الخادم.',
    checkout_redirecting: 'جاري تحويلك إلى قاعدة الحديقة...',
    scan_or_copy: 'امسح أو انسخ للدفع',
    send_exact_amount: 'يرجى إرسال المبلغ المحدد {amount} {currency} لفتح حديقتك الرقمية.',
    upload_screenshot: 'رفع لقطة شاشة الدفع',
    confirm_phone_label: 'تأكيد رقم الهاتف / IPA المستخدم للتحويل',
    mobile_wallet_number: 'رقم المحفظة',
    papara_account: 'حساب Papara',
    secure_card_input: 'إدخال البطاقة بشكل آمن',
    card_number: 'رقم البطاقة',
    card_expiry: 'شهر/سنة',
    card_cvv: 'CVV',
    verifying_payment: 'جاري التحقق من الدفع...',
    payment_required_alert: 'يرجى ملء جميع الحقول المطلوبة',
    drag_drop_browse: 'اسحب وأفلت أو تصفح لقطة شاشة التأكيد',
    screenshot_attached: 'تم إرفاق لقطة الشاشة - انقر للاستبدال',
    encryption_notice: 'يتم تشفير هذه المحادثة عبر بروتوكولات حديقة المعرفة.',
    refresh_analytics: 'تحديث التحليلات',
    close_panel: 'إغلاق',
    tab_cms: 'قاعدة المعرفة (CMS)',
    tab_queries: 'الاستفسارات المعلقة',
    tab_users: 'حسابات الطلاب',
    tab_payments: 'المدفوعات',
    tab_audit_logs: 'سجلات التدقيق',
    tab_quiz_management: 'إدارة الاختبارات',
    tab_quiz_degrees: 'درجات الاختبارات',
    quiz_degrees_title: 'درجات اختبارات جميع المستخدمين',
    quiz_degrees_desc: 'مراجعة نتائج أداء الاختبارات لجميع الطلاب',
    no_quiz_data: 'لا توجد بيانات اختبارات متاحة بعد.',
    loading: 'جار التحميل...',
    name_col: 'الاسم',
    questions_col: 'الأسئلة',
    correct_col: 'صحيح',
    wrong_col: 'خطأ',
    score_col: 'الدرجة',
    stat_student_answers: 'إحصائيات إجابات الطلاب',
    stat_answers_submitted: 'الإجابات المقدمة',
    create_garden: 'إنشاء حديقة',
    embed_seed: 'إضافة بذرة معرفية',
    no_seeds_yet: 'لا توجد بذور مرتبطة بهذه الحديقة بعد.',
    harvest_egypt: 'حصاد مصر',
    harvest_turkey: 'حصاد تركيا',
    seekers_registered: 'الباحثون المسجلون',
    active_now: 'الباحثون النشطون',
    garden_cms_manager: 'مدير زراعة الحدائق',
    cms_subtitle: 'قم بتغذية الدروس والحدائق الرقمية في النظام',
    type_answer_here: 'اكتب الإجابة هنا...',
    no_student_queries: 'لا توجد استفسارات طلابية معلقة! الحديقة نظيفة.',
    weekly_analytics: 'تحليلات الحصاد الأسبوعية',
    edit: 'تعديل',
    del: 'حذف',
    quiz_short: 'اختبار',
    hide_seeds: 'إخفاء البذور',
    view_seeds: 'عرض البذور',
    linked_seeds: 'البذور المرتبطة',
    toggle_access: 'تعديل الوصول',
    reply: 'رد',
    search_mail: 'ابحث في الرسائل...',
    select_mail: 'اختر رسالة آمنة',
    status_online: 'متصل وموثق',
    status_fallback: 'وضع الاختبار فقط',
    verification_secure_key: 'مفتاح التحقق الآمن',
    cryptographic_seal: 'الختم المشفر للنظام البيئي نشط',
    my_gardens_desc_continue: 'حدائقك المشتركة - تابع تعلمك',
    student_growth_metrics: 'معدل نمو الطالب الأكاديمي',
    seeds_bloomed: 'بذور مزهرة',
    currently_studying: 'تدرس حالياً',
    completed: 'مكتمل',
    total_seeds: 'إجمالي البذور',
    no_matching_seeds: 'لا توجد نتائج مطابقة',
    adjust_filters: 'يرجى تغيير خيارات التصفية',
    sort_by: 'الترتيب حسب:',
    default_order: 'الترتيب الافتراضي (المنهج)',
    difficulty_low_high: 'الصعوبة: من الأسهل للأصعب',
    difficulty_high_low: 'الصعوبة: من الأصعب للأسهل',
    duration_short_long: 'المدة: الأقصر أولاً',
    duration_long_short: 'المدة: الأطول أولاً',
    skill_tag_count: 'عدد المهارات: من الأكثر للأقل',
    skill_tag: 'المهارة',
    duration: 'المدة',
    difficulty: 'الصعوبة',
    refine_reorder: 'تصفية وترتيب الدروس',
    reset: 'إعادة تعيين',
    select_difficulty: 'اختر مستوى الصعوبة:',
    select_duration: 'اختر طول الدرس:',
    select_skill_tag: 'اختر مهارة محددة:',
    previous_classroom: 'مسار الفصل:',
    garden_questions_manager: 'مدير أسئلة الحدائق (CMS)',
    seekers_registry: 'سجل الباحثين',
    email_col: 'البريد',
    phone_col: 'الهاتف',
    paid_gardens_col: 'الحدائق المدفوعة',
    verification_col: 'التحقق',
    session_key_col: 'مفتاح الجلسة',
    actions_col: 'الإجراءات',
    session_closed: 'مغلق',
    verified: 'موثق',
    pending_verification: 'قيد التوثيق',
    gardens_count_suffix: 'حديقة',
    none: 'لا يوجد',
    smtp_diagnostics: 'تشخيص نظام البريد (NodeMailer)',
    smtp_status: 'التحقق من خط إرسال البريد المباشر',
    smtp_indicator: 'حالة SMTP:',
    credentials_registry: 'سجل البيانات النشطة',
    smtp_host: 'خادم SMTP:',
    smtp_port: 'منفذ SMTP:',
    smtp_user: 'مستخدم SMTP:',
    smtp_from: 'المرسل:',
    credential_state: 'حالة البيانات:',
    smtp_test: 'اختبار الإرسال المباشر',
    smtp_test_desc: 'إرسال بريد اختباري فوري للتحقق من نظام التسليم.',
    email_placeholder_smtp: 'recipient@example.com',
    sending: 'جارٍ الإرسال...',
    send_test: 'إرسال بريد اختباري',
    quiz_management_title: 'إدارة الاختبارات',
    quiz_management_desc: 'إنشاء وتحرير ومراقبة أسئلة اختبار المعرفة',
    refresh_quiz_data: 'تحديث بيانات الاختبار',
    system_audit_logs: 'سجلات تدقيق النظام',
    audit_log_subtitle: 'سجل غير قابل للتغيير لجميع الإجراءات الإدارية',
    search_logs: 'البحث في السجلات...',
    no_matching_logs: 'لم يتم العثور على سجلات مطابقة.',
    no_logs: 'لم يتم تسجيل أي سجلات تدقيق بعد.',
    no_transactions: 'لم يتم العثور على سجلات معاملات في دفتر الأستاذ.',
    pending_status: 'قيد الانتظار',
    approve_btn: 'موافقة',
    reject_btn: 'رفض',
    export_csv: 'تصدير CSV',
    txn_id_col: 'معرف المعاملة',
    seeker_email_col: 'البريد الإلكتروني',
    garden_id_col: 'معرف الحديقة',
    amount_col: 'المبلغ',
    gateway_col: 'الوسيط',
    proof_col: 'الإثبات',
    status_col: 'الحالة',
    timestamp_col: 'الوقت',
    transaction_history: 'سجل المعاملات',
    audit_log_desc: 'سجل تدقيق لجميع السجلات المالية للطلاب',
    smtp_missing_creds: 'بيانات الاعتماد مفقودة في لوحة الأسرار. ستتم طباعة رموز OTP ديناميكياً عبر وحدة التحكم المحلية وصندوق البريد المحاكي.',
    smtp_dispatch_success: 'تم الإرسال بنجاح!',
    message_id: 'معرف الرسالة:',
    smtp_delivery_refused: 'رفض التسليم:',
    smtp_pass_loaded: 'SMTP_PASS محمل (مؤمن AES-256)',
    not_configured: 'غير مهيأ',
    garden: 'الحديقة',
    seed: 'البذرة',
    confirm_delete: 'هل أنت متأكد تماماً من حذف هذا العنصر؟',
    answer_post_timeout: 'انتهت مهلة إرسال الرد.',
    approval_failed: 'فشل الموافقة',
    approval_request_failed: 'فشل طلب الموافقة',
    rejection_failed: 'فشل الرفض',
    rejection_request_failed: 'فشل طلب الرفض',
    deletion_error: 'خطأ في الحذف',
    cms_update_error: 'خطأ في تحديث CMS',
    bulk_limit_reached: 'تم الوصول للحد الأقصى: سيتم إدراج أول 50 مدخل فقط.',
    populate_lectures: 'يرجى تعبئة شبكة المحاضرات أولاً.',
    select_target_garden: 'يرجى اختيار حديقة مستهدفة صالحة.',
    bulk_insert_failed: 'فشل الإدراج الجماعي على مستوى الخادم.',
    network_upload_error: 'خطأ في رفع الشبكة: ',
    gardens: 'الحدائق',
    all_gardens: 'كل الحدائق',
    back_to_home: 'العودة إلى الصفحة الرئيسية',
    browse_gardens: 'تصفح كل الحدائق',
    discover_courses: 'اكتشف جميع الدورات المتاحة وابدأ التعلم',
    full_name: 'الاسم الكامل',
    full_name_placeholder: 'مثلاً: أحمد علي',
    beginner: 'سهل',
    intermediate: 'متوسط',
    advanced: 'متقدم',
    difficult: 'صعب',
    short_duration: 'قصير (< 15 د)',
    medium_duration: 'متوسط (15-30 د)',
    long_duration: 'طويل (30+ د)',
    payment_verified_pending: 'طلبك قيد المراجعة حالياً. يرجى انتظار موافقة الإدارة.',
    payment_approved: 'تم قبول الدفع!',
    payment_rejected: 'تم رفض الدفع',
    access_activated: 'تم تفعيل وصولك الكامل إلى الحديقة.',
    check_inbox_details: 'يرجى مراجعة البريد الوارد للتفاصيل.',
    skills_acquired: 'تحصيل المهارات والتحكم في بنى الخدمات الموزعة',
    ai_advice: 'نوصي بمتابعة التعلم المستمر لضمان التطور.',
    otp_dispatched: 'تم إرسال رمز التحقق الأمني إلى صندوق الوارد الخاص بك!',
    otp_verified: 'تم توثيق الكود وتوليد تقرير النمو المتكامل بنجاح!',
    report_instruction: 'ارصف وارعى كافة بذور هذه الحديقة بنسبة 100% لتوليد تقرير نموك الأكاديمي.',
    garden_complete: 'تهانينا! الحديقة مزهرة بالكامل 100%!',
    request_report: 'إرسال رمز تقرير النمو والشهادة',
    report_otp_label: 'رمز تحقق التقرير المرسل (OTP)',
    verify_certificate: 'توثيق الرمز وإصدار الشهادة',
    otp_instruction: 'تفقد [صندوق الوارد] بالأعلى للحصول على الرمز.',
    certificate_issued: 'الشهادة الرسمية منقولة للبريد الإلكتروني!',
    view_report: 'استعراض الشهادة وتقرير النمو',
  },
  tr: {
    dir: 'ltr',
    brand: 'Bilgi Bahçesi',
    classroomTitle: 'Bahçe Üssü',
    tagline: 'Becerilerinizi Yetiştirin',
    subtitle: 'Geleceğin dijital ekosisteminde küçük bir tohumdan bir teknoloji devine dönüşün.',
    plant_seed: 'İlk Tohumunu Ek',
    explore: 'Bahçeleri Keşfet',
    available_gardens: 'Mevcut Bahçeler',
    features: 'Özellikler',
    no_gardens_available: 'Şu anda mevcut bahçe bulunmamaktadır.',
    no_garden_seeds: 'Bu bahçede henüz mevcut tohum bulunmamaktadır.',
    choose_spec: 'Yetişmek istediğiniz uzmanlık alanını seçin ve bilgi ekmeye başlayın.',
    total_earnings: 'Toplam Hasat Kazancı',
    active_seekers: 'Aktif Arayıcılar',
    growth_rate: 'Büyüme Oranı',
    brand_subtitle: 'Sinirsel E-Öğrenme Ekosistemi',
    new_era: 'YAZILIM EĞİTİMİNİN YENİ ÇAĞI',
    hero_title_prefix: 'Uzmanlığınızı',
    hero_title_highlight: 'Bilgi Bahçesinde',
    hero_title_suffix: 'Köklendirin',
    realtime_status: 'GERÇEK ZAMANLI ÇEKİRDEK ÇALIŞIYOR',
    plant_skill: 'Tohum Ek',
    open_garden: 'Bahçeyi Aç',
    my_gardens: 'Bahçelerim',
    secure_inbox: 'Güvenli Gelen Kutusu',
    view_profile: 'Profili görüntüle',
    membership_paid: 'ÜCRETLİ',
    membership_free: 'ÜCRETSİZ',
    currency_egp: 'EGP',
    currency_try: 'TRY',
    admin_title: 'Yönetim Paneli',
    system_controller: 'Sistem Denetleyicisi',
    security_logs: 'Güvenlik Günlükleri',
    dashboard: 'Gösterge Paneli',
    analytics: 'Analizler',
    courses: 'Bahçeler',
    users: 'Kullanıcılar',
    settings: 'Ayarlar',
    view_all: 'Hepsini Gör',
    launch_course: 'Yeni Bahçe Başlat',
    last_seen: 'Son Görülme',
    ip_address: 'IP Adresi',
    device: 'Cihaz',
    location: 'Konum',
    search_placeholder: 'İsim veya e-posta ile ara...',
    new_registrations: 'Yeni Kayıtlar',
    avg_growth_rate: 'Ort. Büyüme Oranı',
    security_alerts: 'Güvenlik Uyarıları',
    chat_instructor: 'Eğitmenle Sohbet Et',
    chat_placeholder: 'Eğitene mesajınızı yazın...',
    chat_send: 'Mesaj Gönder',
    chat_transmitting: 'Gönderiliyor...',
    forgot_password: 'Şifrenizi mi Unuttunuz?',
    forgot_password_title: 'Güvenlik Bilgilerini Sıfırla',
    forgot_password_subtitle: 'Senkronizasyon sıfırlama anahtarını almak için e-postanızı girin.',
    send_reset_btn: 'Sıfırlama Anahtarı Gönder',
    reset_success_msg: 'Sıfırlama anahtarı gönderildi! Güvenli gelen kutunuzu kontrol edin.',
    storage_used: 'Depolama Alanı',
    login_title: 'Giriş Yap',
    logout_session: 'Oturumu Kapat',
    email_placeholder: 'gardener@knowledge.io',
    password_placeholder: '••••••••',
    phone_placeholder: '+20123456789 veya +905...',
    sync_key_placeholder: '6 haneli senkronizasyon anahtarı',
    login_subtitle: 'Bilgi Bahçesindeki yolculuğunuza devam edin.',
    email_address: 'E-posta Adresi',
    phone_wallet_num: 'Telefon / Cüzdan Numarası',
    register_subtitle: 'Doğrulanmış ve güvenli bir öğrenci hesabı edinin.',
    email_or_phone: 'E-posta veya Telefon',
    password: 'Şifre',
    already_have_account: 'Zaten hesabınız var mı? Giriş Yapın',
    quick_demo_login: 'Hızlı Sandbox Girişi',
    new_to_garden: 'Bahçede Yeni misiniz?',
    create_account: 'Bahçe Hesabı Oluştur',
    verify_title: 'Kimliği Doğrula',
    verify_subtitle: 'E-posta/telefonunuza güvenli bir doğrulama kodu gönderildi. Lütfen aşağıdaki 6 basamaklı senkronizasyon kodunu girin.',
    verify_btn: 'Gelişimi Doğrula',
    resend_timer: 'Yeniden gönderim süresi',
    resend_btn: 'Kodu Yeniden Gönder',
    classroom_seeds: 'Bilgi Tohumları',
    classroom_rooted: 'Köklendi',
    classroom_path: 'Sınıf Yolu',
    progress_tracking: 'Öğrenme yolculuğunuzu takip edin',
    of: '/',
    total: 'Toplam',
    remaining: 'Kalan',
    ask_question: 'Soru Sor',
    question_placeholder: 'Aklında ne var, bahçıvan? Derinlere kaz...',
    post_btn: 'Soruyu Gönder',
    watermark_text: 'Öğrenci Verisi Korunmaktadır',
    country_switch: 'Ülke',
    egypt: 'Mısır (EGP)',
    turkey: 'Türkiye (TRY)',
    payment_method: 'Ödeme Yöntemi',
    mobile_wallet: 'Mobil Cüzdan (Vodafone Cash)',
    instapay: 'InstaPay Transferi',
    credit_card: 'Kredi / Banka Kartı',
    papara: 'Papara Cüzdanı',
    checkout_title: 'Dijital Bahçe Ödeme',
    checkout_btn: 'Güvenli Büyümeyi Başlat',
    price_label: 'Fiyat',
    secure_badge: 'GÜVENLİ ERİŞİM',
    need_help: 'Yardım mı lazım? Destekle iletişime geçin',
    notebook_title: 'Dijital Not Defteri',
    add_note_btn: 'Notu Kaydet',
    note_placeholder: 'Zaman damgalı bir not, soru veya referans yazın...',
    capture_time: 'Zaman damgası yakala',
    no_notes: 'Not defteriniz boş. Akıllı bir düşünce eklemek için zaman damgası yakalayın!',
    user_page_title: 'Öğrenci Profil Portali',
    user_page_badge: 'ONAYLANMIŞ YETİŞTİRİCİ',
    enrolled_gardens: 'Kayıtlı Bahçeler',
    completed_seeds: 'Tamamlanan Tohumlar',
    account_id: 'Hesap Kimliği',
    security_level: 'Güvenlik Yetkisi',
    membership_tier: 'Üyelik Derecesi',
    registered_phone: 'Bağlı Telefon',
    joined_on: 'Kayıt Tarihi',
    back_to_classroom: 'Sınıfa Geri Dön',
    back_to_landing: 'Bahçelere Geri Dön',
    rights_reserved: 'Tüm hakları saklıdır.',
    my_gardens_desc: 'Bahçeleriniz - Öğrenmeye devam edin',
    enrolled_badge: 'Aktif',
    pending_approval: 'Onay Bekliyor',
    previous_seed: 'Önceki Tohum',
    next_seed: 'Sonraki Tohum',
    no_queries_yet: 'Bu tohum için henüz soru bulunmuyor. İlk soruyu siz sorun!',
    search_notes: 'Notlarında ara...',
    download_notes: 'Notları indir',
    play_from_here: 'Buradan oynat',
    delete_message: 'Mesajı Sil',
    delete_confirm: 'Bu mesajı kalıcı olarak sil?',
    seed_not_completed: 'Tohum henüz tamamlanmadı',
    complete_seed_first: 'Testi açmak için önce tohumu tamamlamalısınız.',
    no_quiz_questions: 'Bu tohum için sınav sorusu bulunmuyor',
    quiz_review: 'Sınav İncelemesi',
    knowledge_check: 'BİLGİ TESTİ',
    question_of: 'Soru {current}/{total}',
    confirm_answer: 'CEVABI ONAYLA',
    checking_answer: 'Yanıt doğrulanıyor...',
    incorrect_review: 'Hatalı cevap. Lütfen tohumu inceleyip tekrar deneyin!',
    try_again_btn: 'YENİDEN DENE',
    correct_excellent: 'Harika! Doğru cevap vererek engeli açtınız!',
    next_question: 'SONRAKİ SORU',
    complete: 'TAMAMLA',
    previous_answer_incorrect: 'Önceki cevabınız yanlıştı. Tekrar deneyin!',
    retry_btn: 'Tekrar Dene',
    correct_answer: 'Doğru cevap!',
    incorrect_try_again: 'Yanlış cevap. Tekrar deneyin!',
    previous: 'Önceki',
    next: 'Sonraki',
    stream_error: 'Video oynatma hatası. Lütfen tekrar deneyin.',
    stream_auth_failed: 'Akış kimlik doğrulaması başarısız.',
    please_complete_checkout: 'Lütfen ödeme işlemini tamamlayın veya akış lisansını yenilemek için tekrar giriş yapın.',
    checkout_success_title: 'Yetkilendirme Başarılı!',
    checkout_transaction_msg: 'İşlem {id} sunucuda doğrulandı.',
    checkout_redirecting: 'Büyüme bağlamı senkronize ediliyor, lütfen bekleyin...',
    scan_or_copy: 'Ödeme için Tara veya Kopyala',
    send_exact_amount: 'Dijital bahçenizin kilidini açmak için lütfen tam {amount} {currency} gönderin.',
    upload_screenshot: 'Ödeme Ekran Görüntüsünü Yükle',
    confirm_phone_label: 'Transfer için kullanılan Telefon/IPA\'nızı onaylayın',
    mobile_wallet_number: 'Mobil Cüzdan Numarası',
    papara_account: 'Papara Cüzdan Hesabı',
    secure_card_input: 'Güvenli Kart Girişi',
    card_number: 'Kart Numarası',
    card_expiry: 'AA/YY',
    card_cvv: 'CVV',
    verifying_payment: 'Ödeme Doğrulanıyor...',
    payment_required_alert: 'Lütfen tüm zorunlu alanları doldurun',
    drag_drop_browse: 'Onay ekran görüntünüzü sürükleyip bırakın veya göz atın',
    screenshot_attached: 'Ekran Görüntüsü Eklendi - Değiştirmek için Tıklayın',
    encryption_notice: 'Bu görüşme Knowledge Garden protokolleri ile uçtan uca şifrelenmiştir.',
    refresh_analytics: 'Analizleri Yenile',
    close_panel: 'Kapat',
    tab_cms: 'Bilgi Tabanı (CMS)',
    tab_queries: 'Bekleyen Sorular',
    tab_users: 'Öğrenci Hesapları',
    tab_payments: 'Ödemeler',
    tab_audit_logs: 'Denetim Günlükleri',
    tab_quiz_management: 'Sınav Yönetimi',
    tab_quiz_degrees: 'Sınav Dereceleri',
    quiz_degrees_title: 'Tüm Kullanıcıların Sınav Dereceleri',
    quiz_degrees_desc: 'Tüm öğrencilerin sınav performans puanlarını inceleyin',
    no_quiz_data: 'Henüz sınav verisi bulunmuyor.',
    loading: 'Yükleniyor...',
    name_col: 'Ad',
    questions_col: 'Sorular',
    correct_col: 'Doğru',
    wrong_col: 'Yanlış',
    score_col: 'Puan',
    stat_student_answers: 'Öğrenci Cevap İstatistikleri',
    stat_answers_submitted: 'Gönderilen Cevaplar',
    create_garden: 'Bahçe Oluştur',
    embed_seed: 'Bilgi Tohumu Ekle',
    no_seeds_yet: 'Bu bahçeye henüz tohum eklenmemiş.',
    harvest_egypt: 'Mısır Hasadı',
    harvest_turkey: 'Türkiye Hasadı',
    seekers_registered: 'Kayıtlı Arayıcılar',
    active_now: 'Aktif Arayıcılar',
    garden_cms_manager: 'Bahçe Yetiştirici Yöneticisi',
    cms_subtitle: 'Sistemdeki dersleri ve dijital bahçeleri besleyin',
    type_answer_here: 'Cevabı buraya yazın...',
    no_student_queries: 'Bekleyen öğrenci sorusu yok! Bahçe temiz.',
    weekly_analytics: 'Haftalık Tohum Hasadı Analizleri',
    edit: 'Düzenle',
    del: 'Sil',
    quiz_short: 'Sınav',
    hide_seeds: 'Tohumları Gizle',
    view_seeds: 'Tohumları Gör',
    linked_seeds: 'Bağlı Tohumlar',
    toggle_access: 'Erişimi Değiştir',
    reply: 'Yanıtla',
    search_mail: 'Yazışmalarda ara...',
    select_mail: 'GÜVENLİ BİR E-POSTA SEÇİN',
    status_online: 'ÇEVRİMİÇİ VE DOĞRULANDI',
    status_fallback: 'YALNIZCA SANDBOX',
    verification_secure_key: 'DOĞRULAMA GÜVENLİK ANAHTARI',
    cryptographic_seal: 'BİLGİ EKOSİSTEMİ KRİPTOGRAFİK MÜHRÜ AKTİF',
    my_gardens_desc_continue: 'Bahçeleriniz - Öğrenmeye devam edin',
    student_growth_metrics: 'Öğrenci Gelişim Analitiği',
    seeds_bloomed: 'Tohum Büyütüldü',
    currently_studying: 'DEVAM EDEN DERS',
    completed: 'Tamamlandı',
    total_seeds: 'toplam tohum',
    no_matching_seeds: 'Eşleşen Sonuç Bulunamadı',
    adjust_filters: 'Filtre kriterlerinizi değiştirmeyi deneyin',
    sort_by: 'Sırala:',
    default_order: 'Varsayılan Sıra (Müfredat)',
    difficulty_low_high: 'Zorluk: Kolaydan Zora',
    difficulty_high_low: 'Zorluk: Zordan Kolaya',
    duration_short_long: 'Süre: Önce En Kısa',
    duration_long_short: 'Süre: Önce En Uzun',
    skill_tag_count: 'Yetenek Sayısı: Çoktan Aza',
    skill_tag: 'Yetenek',
    duration: 'Süre',
    difficulty: 'Zorluk',
    refine_reorder: 'Tohumları Düzenle',
    reset: 'Sıfırla',
    select_difficulty: 'Zorluk Seviyesi Seç:',
    select_duration: 'Ders Süresi Seç:',
    select_skill_tag: 'Belirli Bir Yetenek Seç:',
    previous_classroom: 'Sınıf Yolu:',
    garden_questions_manager: 'Bahçe Soru Yöneticisi (CMS)',
    seekers_registry: 'Arayıcı Kayıt Defteri',
    email_col: 'E-posta',
    phone_col: 'Telefon',
    paid_gardens_col: 'Ücretli Bahçeler',
    verification_col: 'Doğrulama',
    session_key_col: 'Oturum Anahtarı',
    actions_col: 'İşlemler',
    session_closed: 'KAPALI',
    verified: 'Doğrulandı',
    pending_verification: 'Doğrulama Bekliyor',
    gardens_count_suffix: 'BAHÇE',
    none: 'YOK',
    smtp_diagnostics: 'NodeMailer OTP Sistemi Teşhis',
    smtp_status: 'Canlı SMTP hattı ve kimlik bilgileri doğrulanıyor',
    smtp_indicator: 'SMTP Durum Göstergesi:',
    credentials_registry: 'Aktif Kimlik Bilgileri',
    smtp_host: 'SMTP Sunucu:',
    smtp_port: 'SMTP Port:',
    smtp_user: 'SMTP Kullanıcı:',
    smtp_from: 'Gönderici:',
    credential_state: 'Kimlik Durumu:',
    smtp_test: 'SMTP Canlı Test',
    smtp_test_desc: 'Teslimat günlüklerini kontrol etmek için anlık test e-postası gönderir.',
    email_placeholder_smtp: 'recipient@example.com',
    sending: 'Gönderiliyor...',
    send_test: 'Test E-postası Gönder',
    quiz_management_title: 'Sınav Yönetimi',
    quiz_management_desc: 'Bilgi kontrol soruları oluşturun, düzenleyin ve izleyin',
    refresh_quiz_data: 'Sınav Verilerini Yenile',
    system_audit_logs: 'Sistem Denetim Günlükleri',
    audit_log_subtitle: 'Tüm yönetim işlemlerinin değiştirilemez kaydı',
    search_logs: 'Günlüklerde ara...',
    no_matching_logs: 'Eşleşen günlük kaydı bulunamadı.',
    no_logs: 'Henüz denetim günlüğü kaydedilmedi.',
    no_transactions: 'Defterde işlem kaydı bulunamadı.',
    pending_status: 'BEKLEMEDE',
    approve_btn: 'Onayla',
    reject_btn: 'Reddet',
    export_csv: 'CSV Dışa Aktar',
    txn_id_col: 'İşlem ID',
    seeker_email_col: 'E-posta',
    garden_id_col: 'Bahçe ID',
    amount_col: 'Tutar',
    gateway_col: 'Ödeme Yöntemi',
    proof_col: 'Kanıt',
    status_col: 'Durum',
    timestamp_col: 'Tarih',
    transaction_history: 'İşlem Geçmişi',
    audit_log_desc: 'Tüm öğrenci finansal kayıtlarının denetim günlüğü',
    smtp_missing_creds: 'Gizli Panelde kimlik bilgileri eksik. Kayıt ve Rapor OTP kodları yalnızca yerel sanal konsol ve simüle edilmiş posta tepsisi üzerinden dinamik olarak yazdırılacak.',
    smtp_dispatch_success: 'Gönderim Başarılı!',
    message_id: 'Mesaj ID:',
    smtp_delivery_refused: 'Teslimat Reddedildi:',
    smtp_pass_loaded: 'SMTP_PASS Yüklendi (AES-256 Korumalı)',
    not_configured: 'Yapılandırılmamış',
    garden: 'Bahçe',
    seed: 'Tohum',
    confirm_delete: 'Bu öğeyi silmek istediğinizden emin misiniz?',
    answer_post_timeout: 'Yanıt gönderme zaman aşımına uğradı.',
    approval_failed: 'Onay başarısız',
    approval_request_failed: 'Onay talebi başarısız',
    rejection_failed: 'Reddetme başarısız',
    rejection_request_failed: 'Reddetme talebi başarısız',
    deletion_error: 'Silme Hatası',
    cms_update_error: 'CMS Güncelleme Hatası',
    bulk_limit_reached: 'Fiber CDN Sınırına ulaşıldı: Yalnızca ilk 50 kayıt işlenecek.',
    populate_lectures: 'Lütfen önce ders listesini doldurun.',
    select_target_garden: 'Lütfen geçerli bir hedef bahçe seçin.',
    bulk_insert_failed: 'Sunucuda toplu ekleme başarısız.',
    network_upload_error: 'Ağ yükleme hatası: ',
    gardens: 'Bahçeler',
    all_gardens: 'Tüm Bahçeler',
    back_to_home: 'Ana Sayfaya Dön',
    browse_gardens: 'Tüm Bahçeleri Keşfet',
    discover_courses: 'Mevcut tüm kursları keşfedin ve öğrenmeye başlayın',
    full_name: 'Tam Ad',
    full_name_placeholder: 'Örn: Ahmet Yılmaz',
    beginner: 'Kolay',
    intermediate: 'Orta',
    advanced: 'İleri',
    difficult: 'Zor',
    short_duration: 'Kısa (< 15 dk)',
    medium_duration: 'Orta (15-30 dk)',
    long_duration: 'Uzun (30+ dk)',
    payment_verified_pending: 'Ödemeniz doğrulanıyor. Lütfen yönetici onayını bekleyin.',
    payment_approved: 'Ödeme Onaylandı!',
    payment_rejected: 'Ödeme Reddedildi',
    access_activated: 'Tam bahçe erişiminiz etkinleştirildi.',
    check_inbox_details: 'Ayrıntılar için gelen kutunuzu kontrol edin.',
    skills_acquired: 'Müfredat Becerileri ve Dağıtık Sistem Yönetimi',
    ai_advice: 'Gelişimi sağlamak için sürekli öğrenmeye devam etmenizi öneriyoruz.',
    otp_dispatched: 'Güvenlik doğrulama şifresi e-postanıza gönderildi!',
    otp_verified: 'Şifre doğrulandı, Gelişim Raporunuz oluşturuldu!',
    report_instruction: 'Akademik gelişim raporunuzu almak için bu bahçedeki tüm tohumları %100 büyütmelisiniz.',
    garden_complete: 'Tebrikler! Bahçe yetiştiriciliği %100 tamamlandı!',
    request_report: 'Gelişim Raporu ve Sertifika Şifresi Gönder',
    report_otp_label: 'E-POSTA DOĞRULAMA ŞİFRESİ (OTP)',
    verify_certificate: 'Şifreyi Doğrula',
    otp_instruction: 'Şifreyi bulmak için yukarıdaki [Gelen Kutusu] simgesine tıklayın.',
    certificate_issued: 'Sertifikanız E-postaya Gönderildi!',
    view_report: 'Sertifika ve Raporu Görüntüle',
  }
};
